---
title: "post_training"
output: html_document
---

```{r}
require(dplyr)
require(reshape2)
source("code/fns.R")
require(matrixStats)
require(ggplot2)
# long_durations <- data.frame(species_id = c(12, 2, 20, 22, 23, 23.4, 6, 7, 8, 9), name = "bad")

data_key <- list.files("output/processed_data_set4/", pattern="key", full.names = TRUE)
data_key <- do.call(rbind, lapply(1:length(data_key), function(x) readRDS(data_key[x])))

durations <- data_key %>%
  mutate(duration = round(duration, digits=3)) %>%
  group_by(species_id, multiplier) %>%
  summarise(duration = max(duration)) %>%
  mutate(species_id = as.character(species_id))

train_key <- list.files("output/trained_models_set5/", pattern="res", full.names=TRUE)
train_key <- do.call(rbind, lapply(1:length(train_key), function(x) readRDS(train_key[x])))

train_key$ver <- do.call(rbind, strsplit(train_key$results_name,"_"))[,4]

quick_check <- train_key %>%
  # filter(ver == "V1") %>%
  filter(species_id %in% c(12, 13, 14, 15)) %>%
  mutate(total_test = test_positive + test_negatve) %>%
  mutate(wrong1 = (total_test-1)/total_test) %>%
  mutate(wrong2 = (total_test-2)/total_test) %>%
  mutate(wrong3 = (total_test-3)/total_test) %>%
  mutate(wrong4 = (total_test-4)/total_test) %>%
  # mutate(over98 = test_accuracy >= 0.979,
  #        over96 = test_accuracy < 0.979 & test_accuracy >= 0.959) %>%
  group_by(ver, file_name, wrong1, wrong2, wrong3, wrong4, species_id) %>%
  summarise(max_acc = round(max(test_accuracy), digits=2),
            mean_acc = round(mean(test_accuracy), digits=2),
            n_at_wrong1 = length(which(test_accuracy >= wrong1 - 0.001)),
            n_at_wrong2 = length(which(test_accuracy >= wrong2 - 0.001 & test_accuracy < wrong1 - 0.001)),
            n_at_wrong3 = length(which(test_accuracy >= wrong3 - 0.001 & test_accuracy < wrong2 - 0.001)),
            # n_at_wrong3 = length(which(test_accuracy >= wrong4 - 0.001 & test_accuracy < wrong3 - 0.001)),
            max_iter = max(iter), .groups = 'drop')

top_res <- train_key %>%
  filter(ver != "V1") %>%
  group_by(species_id) %>%
  # select(-dim_x, -dim_y) %>%
  arrange(-test_accuracy) %>%
  slice_max(test_accuracy, n=1) %>%
  slice_min(test_loss, n=1) %>%
  left_join(., durations, by = "species_id") %>%
  mutate(multiplier = ifelse(species_id == 13.4, 2.5, multiplier))  %>%
  mutate(multiplier = ifelse(species_id == 5.4, 3, multiplier))

top_res <- top_res %>%
  filter(!(species_id %in% c("13.4", "5.4", "20.4")))

```

```{r}
require(dplyr)
require(ggplot2)

files1 <- list.files("results_proba", full.names = TRUE)
files2 <- list.files("bash/results_proba", full.names = TRUE)

res1 <- do.call(rbind, lapply(1:length(files1), function(x) readRDS(files1[x])))
res2 <- do.call(rbind, lapply(1:length(files2), function(x) readRDS(files2[x])))

res <- data.frame(res2) %>%
  rename(recording_id = file_name, file_id = test_files) %>%
  rbind(res1,.) %>%
  mutate(class = as.numeric(as.character(class)),
         prob0 = as.numeric(as.character(prob0)),
         prob1 = as.numeric(as.character(prob1))) 

res <- res %>%
  mutate(parent_species = do.call(rbind, strsplit(res$species_id, "[.]"))[,1]) 

test <- res %>%
  # filter(prob1 > 0.5) %>%
  # filter(species_id == 21) %>%
  group_by(recording_id, file_id, species_id, parent_species) %>%
  mutate(max_row = n(), row_seq = 1:n())  %>%
  mutate(frame = c(rep("f1",unique(max_row)/3), rep("f2",unique(max_row)/3), rep("f3", unique(max_row)/3))) %>%
  # mutate(frame = ifelse(row_seq <= max_row/, "f1", "f2")) %>%
  ungroup() %>%
  group_by(recording_id, file_id, species_id, frame, parent_species) %>%
  mutate(frame_seq = 1:n())
```


```{r fig.height=10, fig.width=24}
toplot <- sample(unique(test$recording_id),6)

test %>%
  filter(recording_id %in% toplot) %>%
  ggplot(aes(x=frame_seq, col=as.character(frame), y=prob1)) +
  ylim(0,1) +
  geom_line() +
  facet_grid(recording_id~species_id, scales="free")  + 
  theme(legend.position="none")

```

```{r}
tmp <- quantile(test[test$species_id == "0",]$prob1, seq(0, 1, 0.01), na.rm=TRUE)
tmp[99]

quantile_summary <- test %>%
  group_by(parent_species) %>%
  summarise(quan1 = quantile(prob1, seq(0,1,0.01))[99])

test2 <- test %>%
  # filter(class == 0) %>%
  group_by(recording_id, file_id, parent_species, class, frame_seq) %>%
  summarise(prob1 = max(prob1),
            prob0 = max(prob0)) %>%
  filter(prob1 > prob0)

test3 <- test2 %>%
  group_by(recording_id, parent_species) %>%
  summarise(prob1 = max(prob1)) %>%
  left_join(., quantile_summary) %>%
  filter(prob1 >= quan1)

export <- test3 %>%
  mutate(parent_species = paste0("s", parent_species)) %>%
  select(parent_species, recording_id, prob1) %>%
  dcast(recording_id ~ parent_species) %>%
  mutate_all(., function(x) ifelse(is.na(x), 0, x))
```

```{r}
template <- read.csv("data/sample_submission.csv")

export <- export[match(template$recording_id, export$recording_id),]

missing_species <- colnames(template)[!(colnames(template) %in% colnames(export))]
if(length(missing_species) > 0){
  missing_tmp <- data.frame(matrix(0, nrow=nrow(export), ncol=length(missing_species)))
  colnames(missing_tmp) <- missing_species
  export <- cbind(missing_tmp, export) 
}
export <- export[,match(colnames(template), colnames(export))]

dim(export) == dim(template)
write.csv(export, "submissions/results_proba4.csv", row.names = F, quote = F)

```


```{r}
filter(species_id == "17.4") %>%
  filter(prob1 > 0 ) %>%
  arrange(-prob1)
  filter(recording_id %in% toplot) %>%
  ggplot(aes(x=frame_seq, col=as.character(frame), y=prob1)) +
  ylim(0,1) +
  geom_line() +
  facet_grid(recording_id~species_id, scales="free")  + 
  theme(legend.position="none")

test2 %>%
  select(prob1, frame_seq, frame) %>%
  dcast(frame_seq  ~ frame, value.var = "prob1") %>%
  mutate(average_conf = (f1 + f2 + f3)/3)
```


```{r}
template <- read.csv("data/sample_submission.csv")

list_res <- list.files("results", full.names = TRUE)

res <- do.call(rbind, lapply(1:length(list_res), function(x) readRDS(list_res[x]))) 
res <- res %>%
  mutate(parent_species = do.call(rbind, strsplit(res$species_id, "[.]"))[,1]) 

res2 <- res %>%
  mutate(predictions = ifelse(value == 1, 0, 1))

```


```{r}
dat <- res2 %>%
  group_by(parent_species, recording_id, file_id) %>%
  summarise(predictions = (max(predictions))) %>%
  mutate(parent_species = paste0("s", parent_species)) %>%
  select(parent_species, recording_id, predictions) %>%
  dcast(recording_id ~ parent_species)

dat <- dat[match(template$recording_id, dat$recording_id),]
dat <- dat[,match(colnames(template), colnames(dat))]

write.csv(dat, "results_mean3.csv", row.names = F, quote = F)

```


```{r}

dat <- res %>%
  group_by(parent_species, recording_id, file_id) %>%
  summarise(value = (median(value))) %>%
  mutate(parent_species = paste0("s", parent_species)) %>%
  select(parent_species, recording_id, value) %>%
  dcast(recording_id ~ parent_species)

dat <- dat[match(template$recording_id, dat$recording_id),]
dat <- dat[,match(colnames(template), colnames(dat))]

write.csv(dat, "results_median.csv", row.names = F, quote = F)


```


```{r}
test_files_full <- list.files("data/test_wav", pattern="wav", full.names = TRUE)
test_files_full <- data.frame(recording_id = do.call(rbind, strsplit(test_files_full, "/|.wav"))[,4], file_id = test_files_full)

file_name <- "01812f522"
test <- specmaker(test_files_full[test_files_full$recording_id ==file_name,], low_f = 50, high_f = 8500, window_multiplier=2.5)  %>%
      group_by(FreqHz) %>%
      mutate(value = value - mean(value)) %>%
      ungroup() %>%
      mutate(value = (value - min(value)) / (max(value) - min(value))) %>%
      mutate(zts = seqt - min(seqt))

test <- test %>%
    group_by(zts) %>%
    mutate(value = value - mean(value)) %>%
    ungroup()  %>%
    mutate(value = scale(value, center=TRUE)) %>%
    mutate(value = ifelse(value < 0, 0, value))

test %>% 
  ggplot(aes(x = zts, y = FreqHz, col = value)) +
  geom_tile() + 
  ggtitle(test_files_full[test_files_full$recording_id ==file_name,]) +
  scale_color_gradient2(low = ("white"), mid = "white", high = ("red")) + theme_bw()

```


```{r}
  tmp <- data  %>%
    mutate(cat1 = ifelse(cate == "true_positive", 1, 0),
           cat2 = ifelse(cate == "false_positive", 1, 0)) %>%
    group_by(unique_id) %>%
    mutate(zts = seqt - min(seqt)) %>%
    ungroup() %>%
    select(unique_id, cat1, cat2, FreqHz, value, zts)
  
  freq_bin <- data.frame(FreqHz = unique(tmp$FreqHz), 
                         FreqBin1 = cut(unique(tmp$FreqHz), 4, labels = c(1,1,2,2)),
                         FreqBin2 = cut(unique(tmp$FreqHz), 4, labels = c(0,3,3,0)))

  
  f1 <- tmp %>%
    left_join(., freq_bin, by="FreqHz") %>%
    dplyr::filter(FreqBin1 == 1) %>%
    dcast(unique_id + cat1 + cat2 + zts ~ FreqHz) 
  
  f2 <- tmp %>%
    left_join(., freq_bin, by="FreqHz") %>%
    dplyr::filter(FreqBin1 == 2) %>%
    dcast(unique_id + cat1 + cat2 + zts ~ FreqHz)
  
  f3 <- tmp %>%
    left_join(., freq_bin, by="FreqHz") %>%
    dplyr::filter(FreqBin2 == 3) %>%
    dcast(unique_id + cat1 + cat2 + zts ~ FreqHz) 
  
  lister <- function(x){
    list(f1 %>% dplyr::filter(zts ==times[x])%>%select(-unique_id, -cat1, -cat2, -zts) %>% as.matrix(),
         f2 %>% dplyr::filter(zts ==times[x])%>%select(-unique_id, -cat1, -cat2, -zts) %>% as.matrix(),
         f3 %>% dplyr::filter(zts ==times[x])%>%select(-unique_id, -cat1, -cat2, -zts) %>% as.matrix())
  }
  
  times <- unique(tmp$zts)
  train <- lapply(1:length(times), function(x) lister(x))
  output_x <- array(c(as.numeric(unlist(train))), dim=c(dim(train[[1]][[1]]), length(train), length(train[[1]])))
  output_x_lab <- f1 %>% dplyr::filter(zts == 0) %>% select(cat2) %>% as.matrix() %>% keras::to_categorical() 



```


```{r}

keras_prepper <- function(input_data){
  tmp <- input_data  %>%
    mutate(cat1 = ifelse(cate == "true_positive", 1, 0),
           cat2 = ifelse(cate == "false_positive", 1, 0)) %>%
    group_by(unique_id) %>%
    mutate(zts = seqt - min(seqt)) %>%
    ungroup() %>%
    select(unique_id, cat1, cat2, FreqHz, value, zts)
  
  freq_bin <- data.frame(FreqHz = unique(tmp$FreqHz), FreqBin = cut(unique(tmp$FreqHz), 4, labels = c(1,2,3,4)))
  
  f1 <- tmp %>%
    left_join(., freq_bin, by="FreqHz") %>%
    filter(FreqBin == 1) %>%
    dcast(unique_id + cat1 + cat2 + zts ~ FreqHz) 
  
  f2 <- tmp %>%
    left_join(., freq_bin, by="FreqHz") %>%
    filter(FreqBin == 2) %>%
    dcast(unique_id + cat1 + cat2 + zts ~ FreqHz)
  
  
  f3 <- tmp %>%
    left_join(., freq_bin, by="FreqHz") %>%
    filter(FreqBin == 3) %>%
    dcast(unique_id + cat1 + cat2 + zts ~ FreqHz) 
  
  f4 <- tmp %>%
    left_join(., freq_bin, by="FreqHz") %>%
    filter(FreqBin == 4) %>%
    dcast(unique_id + cat1 + cat2 + zts ~ FreqHz) 
  
  lister <- function(x){
    list(f1 %>% filter(zts ==times[x])%>%select(-unique_id, -cat1, -cat2, -zts) %>% as.matrix(),
         f2 %>% filter(zts ==times[x])%>%select(-unique_id, -cat1, -cat2, -zts) %>% as.matrix(),
         f3 %>% filter(zts ==times[x])%>%select(-unique_id, -cat1, -cat2, -zts) %>% as.matrix(),
         f4 %>% filter(zts ==times[x])%>%select(-unique_id, -cat1, -cat2, -zts) %>% as.matrix())
  }
  
  times <- unique(tmp$zts)
  train <- lapply(1:length(times), function(x) lister(x))
  output_x <- array(c(as.numeric(unlist(train))), dim=c(dim(train[[1]][[1]]), length(train), length(train[[1]])))
  output_x_lab <- f1 %>% filter(zts == 0) %>% select(cat2) %>% as.matrix() %>% keras::to_categorical() 
  return(list(output_x, output_x_lab))
}




```



```{r}
tmp <- dat 
tmp$total_accuracy <- 0
tmp$total_loss <- 0
tmp$diff <- abs(tmp$total_accuracy - tmp$test_accuracy)

res_list <- vector('list', nrow(tmp))
for(i in 1:nrow(tmp)){
  model1 <- keras::load_model_hdf5(tmp$results_name[i])
  res_list[[i]] <- data.frame(pred_x = model1 %>% keras::predict_classes(train))
  tmp$total_accuracy[i] <- model1 %>% keras::evaluate(train, train_lab) %>% .[[2]]
  tmp$total_loss[i] <- model1 %>% keras::evaluate(train, train_lab) %>% .[[1]]
  }
res <- do.call(cbind, res_list) 
colnames(res) <- seq(1, ncol(res), 1)

score_return <- function(input, use_weights=FALSE){
  test <- input %>% 
  mutate(weight = total_accuracy/test_accuracy)
  
  selected <- res[, colnames(res) %in% test$iter]
  
  if(use_weights == TRUE){
    raw <- rowMeans2(as.matrix(selected))
    return(mean(abs(train_lab[,2] - raw)))
  } else {
    
    weighted <- rowWeightedMeans(as.matrix(selected), w = test$weight)
    return(mean(abs(train_lab[,2] - weighted)))
  }
  }

incre <- seq(0.85, 0.96, 0.01)
total_n <- do.call(rbind, lapply(1:length(incre), function(x) nrow(tmp %>% filter(total_accuracy >= incre[x]))))
test_n <- do.call(rbind, lapply(1:length(incre), function(x) nrow(tmp %>% filter(test_accuracy >= incre[x]))))
total <- do.call(rbind, lapply(1:length(incre), function(x) score_return(use_weight = FALSE, tmp %>% filter(total_accuracy >= incre[x]))))
test <- do.call(rbind, lapply(1:length(incre), function(x) score_return(use_weight = FALSE, tmp %>% filter(test_accuracy >= incre[x]))))

weighted <- data.frame(incre, total_n, total=total, test_n, test = test)
# raw <- data.frame(incre, total_n, total=total, test_n, test = test)

key
#####

```


